In [1]:
import numpy as num 

In [2]:
a = num.array([(1,2,3),(4,5,6)])

In [3]:
print("the array is",a)

the array is [[1 2 3]
 [4 5 6]]


In [7]:
numpsy vs listsss


we use numpy beacuse--

--it occupy less memory
--fast
--convinent

SyntaxError: invalid syntax (<ipython-input-7-b53ba50c1dc8>, line 1)

In [9]:
import numpy as nm

In [10]:
import time

In [11]:
import sys

In [18]:
s=range(1000)
print(sys.getsizeof(5)*len(s))  //memory occupied by list

28000


In [21]:
d=nm.arange(1000)
print(d.size*d.itemsize)   //memory occupied by mumpy

4000


In [1]:
import numpy as num


In [2]:
a=num.array([(1,2,3),(4,5,6)])   //by using this we conclude about the dimesionality of an array

In [4]:
print(a.ndim)

2


In [5]:
import numpy as nm

In [11]:
a=nm.array([(1,2,3)])   // it will give the info about the occupied memory by each

In [12]:
print(a.itemsize)

4


In [13]:
import numpy as numm

In [14]:
a=numm.array([(1,2,3),(5,6,7)])

In [15]:
print(a.dtype)       // data type

int32


In [16]:
print(a.size)  //it will give the size of array

6


In [17]:
print(a.shape)  // it give the number of rows and columns

(2, 3)


In [19]:
import numpy as numn

In [21]:
a=numn.array([(1,23,4),(3,4,5)])

In [24]:
a=a.reshape(3,2)   //reshaping

In [25]:
print(a)

[[ 1 23]
 [ 4  3]
 [ 4  5]]


In [28]:
print(a[0,1])   //if you want to access perticular number

23


In [30]:
print(a[0:,1])   

[23  3  5]


In [34]:
import numpy as num

In [41]:
a=num.linspace(1,3,10) //it will give the equally divided number  

In [42]:
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [43]:
import numpy as nm

In [44]:
a=nm.array([(1,23,4),(3,4,5)])

In [45]:
print(a.max()) //max

23


In [46]:
print(a.min())  //min

1


In [47]:
print(a.sum())  //sum

40


In [48]:
print(a.sum(axis=0))

[ 4 27  9]


In [49]:
print (nm.sqrt(a))  //squareroot

[[1.         4.79583152 2.        ]
 [1.73205081 2.         2.23606798]]


In [50]:
print(num.std(a))  //std deviation

7.4087035902976215


In [51]:
a=numn.array([(1,23,4),(3,4,5)])

b=numn.array([(1,23,4),(3,4,5)])

In [52]:
print(a+b)    //addition

[[ 2 46  8]
 [ 6  8 10]]


In [53]:
print(a-b)  //substaraction

[[0 0 0]
 [0 0 0]]


In [54]:
print(a/b)   // division

[[1. 1. 1.]
 [1. 1. 1.]]


In [55]:
print(a*b)       // multipication

[[  1 529  16]
 [  9  16  25]]


In [60]:
print(numn.vstack((a,b)))

[[ 1 23  4]
 [ 3  4  5]
 [ 1 23  4]
 [ 3  4  5]]


In [61]:
print(numn.hstack((a,b)))

[[ 1 23  4  1 23  4]
 [ 3  4  5  3  4  5]]


In [63]:
print(a.ravel())

[ 1 23  4  3  4  5]
